package main

import (
	"fmt"
	"os"

	"github.com/user/go-frontol-loader/pkg/config"
	"github.com/user/go-frontol-loader/pkg/ftp"
)

func main() {
	// Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to load configuration: %v\n", err)
		os.Exit(1)
	}

	// Connect to FTP
	client, err := ftp.NewClient(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to connect to FTP: %v\n", err)
		os.Exit(1)
	}
	defer func() {
		if err := client.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to close FTP client: %v\n", err)
		}
	}()

	fmt.Println("=== FTP Diagnostic Tool ===")
	fmt.Printf("FTP Host: %s:%d\n", cfg.FTPHost, cfg.FTPPort)
	fmt.Printf("FTP User: %s\n", cfg.FTPUser)
	fmt.Printf("Request Dir: %s\n", cfg.FTPRequestDir)
	fmt.Printf("Response Dir: %s\n", cfg.FTPResponseDir)
	fmt.Println()

	// Get all kassa folders
	folders := ftp.GetAllKassaFolders(cfg)
	fmt.Printf("Found %d kassa folders\n\n", len(folders))

	totalFiles := 0
	for _, folder := range folders {
		fmt.Printf("Kassa: %s, Folder: %s\n", folder.KassaCode, folder.FolderName)
		fmt.Printf("  Request path: %s\n", folder.RequestPath)
		fmt.Printf("  Response path: %s\n", folder.ResponsePath)

		// Check request folder
		requestFiles, err := client.ListFiles(folder.RequestPath)
		if err != nil {
			fmt.Printf("  ERROR listing request folder: %v\n", err)
		} else {
			fmt.Printf("  Request files: %d\n", len(requestFiles))
			for _, f := range requestFiles {
				fmt.Printf("    - %s\n", f.Name)
			}
		}

		// Check response folder
		responseFiles, err := client.ListFiles(folder.ResponsePath)
		if err != nil {
			fmt.Printf("  ERROR listing response folder: %v\n", err)
		} else {
			fmt.Printf("  Response files: %d\n", len(responseFiles))
			for _, f := range responseFiles {
				fmt.Printf("    - %s\n", f.Name)
			}
			totalFiles += len(responseFiles)
		}
		fmt.Println()
	}

	fmt.Printf("=== Summary ===\n")
	fmt.Printf("Total response files found: %d\n", totalFiles)
	if totalFiles == 0 {
		fmt.Println("\nWARNING: No files found in response folders!")
		fmt.Println("Possible reasons:")
		fmt.Println("  1. Files haven't been generated by Frontol yet")
		fmt.Println("  2. Request.txt files weren't sent")
		fmt.Println("  3. Wait time (WAIT_DELAY_MINUTES) is too short")
		fmt.Println("  4. Frontol system is not processing requests")
	}
}
