package models

import "strings"

type TxColumnKind int

const (
	TxColumnString TxColumnKind = iota
	TxColumnInt64
	TxColumnFloat64
	TxColumnDate
	TxColumnTime
	TxColumnSource
)

type TxColumnSpec struct {
	Name      string
	Kind      TxColumnKind
	AllowZero bool
}

var TxSchemas = map[string][]TxColumnSpec{
	"tx_bill_registration_21_23": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bill_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bill_denomination", Kind: TxColumnFloat64},
		{Name: "bill_quantity", Kind: TxColumnFloat64},
		{Name: "bill_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "reserved_17", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bill_storno_22_24": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bill_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bill_denomination", Kind: TxColumnFloat64},
		{Name: "bill_quantity", Kind: TxColumnFloat64},
		{Name: "bill_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "reserved_17", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_accrual_9": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "bonus_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "activation_date", Kind: TxColumnString},
		{Name: "expiration_date", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_payment_32": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bonus_card_number", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_payment_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_change_amount", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_payment_33": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bonus_card_number", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_payment_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_change_amount", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_payment_82": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bonus_card_number", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_payment_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_change_amount", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_payment_83": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "bonus_card_number", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_payment_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_change_amount", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_bonus_refund_10": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "bonus_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "bonus_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "activation_date", Kind: TxColumnString},
		{Name: "expiration_date", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_card_status_change_27": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "card_number", Kind: TxColumnString},
		{Name: "card_type_code", Kind: TxColumnString},
		{Name: "card_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnFloat64},
		{Name: "event_code", Kind: TxColumnFloat64},
		{Name: "reserved_17", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "old_card_status", Kind: TxColumnInt64, AllowZero: true},
		{Name: "new_card_status", Kind: TxColumnInt64, AllowZero: true},
		{Name: "new_valid_from", Kind: TxColumnString},
		{Name: "new_valid_to", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_cash_in_50": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_cash_out_51": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_counter_change_57": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "card_or_client_code", Kind: TxColumnString},
		{Name: "card_type_code", Kind: TxColumnString},
		{Name: "binding_type", Kind: TxColumnFloat64},
		{Name: "value_after_changes", Kind: TxColumnFloat64},
		{Name: "change_amount", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "reserved_17", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "counter_valid_from", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "card_valid_from", Kind: TxColumnString},
		{Name: "card_valid_to", Kind: TxColumnString},
		{Name: "counter_valid_to", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_document_cancel_56": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_clients_65": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_close_55": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_close_gp_49": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_close_kkt_45": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_discount_35": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_document_discount_37": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_document_discount_85": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_document_discount_87": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_document_egais_120": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_non_fin_close_58": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_open_42": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "customer_card_numbers", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "customer_code", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "order_id", Kind: TxColumnString},
		{Name: "document_amount_without_discounts", Kind: TxColumnFloat64},
		{Name: "visitor_count", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "base_document_number", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "employee_edit_document_number", Kind: TxColumnInt64},
		{Name: "department_code", Kind: TxColumnString},
		{Name: "hall_code", Kind: TxColumnInt64},
		{Name: "service_point_code", Kind: TxColumnInt64},
		{Name: "reservation_id", Kind: TxColumnString},
		{Name: "user_variables", Kind: TxColumnString},
		{Name: "external_comment", Kind: TxColumnString},
		{Name: "revaluation_datetime", Kind: TxColumnDate},
		{Name: "contractor_code", Kind: TxColumnInt64},
		{Name: "subdivision_id", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "document_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_document_rounding_38": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_employee_accounting_doc_26": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_employee_accounting_pos_29": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_employee_registration_25": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "reserved_17", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_fiscal_payment_40": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "card_number", Kind: TxColumnString},
		{Name: "payment_type_code", Kind: TxColumnString},
		{Name: "payment_type_operation", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "customer_amount_payment_currency", Kind: TxColumnFloat64},
		{Name: "customer_amount_base_currency", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "current_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "currency_code", Kind: TxColumnInt64},
		{Name: "cash_out_amount", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_fiscal_payment_43": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "card_number", Kind: TxColumnString},
		{Name: "payment_type_code", Kind: TxColumnString},
		{Name: "payment_type_operation", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "customer_amount_payment_currency", Kind: TxColumnFloat64},
		{Name: "customer_amount_base_currency", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "current_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "currency_code", Kind: TxColumnInt64},
		{Name: "cash_out_amount", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "ps_protocol_number", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_item_kkt_6_16": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "item_identifier", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "quantity_kkt", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "final_price_kkt_currency", Kind: TxColumnFloat64},
		{Name: "position_total_amount_kkt_currency", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "article_sku", Kind: TxColumnString},
		{Name: "registration_barcode", Kind: TxColumnString},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "kkt_section", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "split_pack_quantity", Kind: TxColumnInt64},
		{Name: "gift_card_external_number", Kind: TxColumnString},
		{Name: "pack_quantity", Kind: TxColumnInt64},
		{Name: "item_type_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "marking_code", Kind: TxColumnString},
		{Name: "excise_marks", Kind: TxColumnString},
		{Name: "personal_modifier_group_code", Kind: TxColumnString},
		{Name: "stoloto_registration_time", Kind: TxColumnDate},
		{Name: "stoloto_ticket_id", Kind: TxColumnInt64},
		{Name: "reserved_38", Kind: TxColumnInt64},
		{Name: "alc_code", Kind: TxColumnString},
		{Name: "reserved_40", Kind: TxColumnFloat64},
		{Name: "prescription_data_1", Kind: TxColumnString},
		{Name: "prescription_data_2", Kind: TxColumnString},
		{Name: "position_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_item_registration_1_11": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "item_identifier", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "price_without_discounts", Kind: TxColumnFloat64},
		{Name: "quantity", Kind: TxColumnFloat64},
		{Name: "position_amount_with_rounding", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "final_price", Kind: TxColumnFloat64},
		{Name: "position_total_amount", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "article_sku", Kind: TxColumnString},
		{Name: "registration_barcode", Kind: TxColumnString},
		{Name: "position_amount_base", Kind: TxColumnFloat64},
		{Name: "kkt_section", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "split_pack_quantity", Kind: TxColumnInt64},
		{Name: "gift_card_external_number", Kind: TxColumnString},
		{Name: "pack_quantity", Kind: TxColumnInt64},
		{Name: "item_type_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "marking_code", Kind: TxColumnString},
		{Name: "excise_marks", Kind: TxColumnString},
		{Name: "personal_modifier_group_code", Kind: TxColumnString},
		{Name: "stoloto_registration_time", Kind: TxColumnDate},
		{Name: "stoloto_ticket_id", Kind: TxColumnInt64},
		{Name: "reserved_38", Kind: TxColumnInt64},
		{Name: "alc_code", Kind: TxColumnString},
		{Name: "reserved_40", Kind: TxColumnFloat64},
		{Name: "prescription_data_1", Kind: TxColumnString},
		{Name: "prescription_data_2", Kind: TxColumnString},
		{Name: "position_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_item_storno_2_12": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "item_identifier", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "price_without_discounts", Kind: TxColumnFloat64},
		{Name: "quantity", Kind: TxColumnFloat64},
		{Name: "position_amount_with_rounding", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "final_price", Kind: TxColumnFloat64},
		{Name: "position_total_amount", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "article_sku", Kind: TxColumnString},
		{Name: "registration_barcode", Kind: TxColumnString},
		{Name: "position_amount_base", Kind: TxColumnFloat64},
		{Name: "kkt_section", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "comment_code", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "employee_code", Kind: TxColumnInt64},
		{Name: "split_pack_quantity", Kind: TxColumnInt64},
		{Name: "gift_card_external_number", Kind: TxColumnString},
		{Name: "pack_quantity", Kind: TxColumnInt64},
		{Name: "item_type_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "marking_code", Kind: TxColumnString},
		{Name: "excise_marks", Kind: TxColumnString},
		{Name: "personal_modifier_group_code", Kind: TxColumnString},
		{Name: "stoloto_registration_time", Kind: TxColumnDate},
		{Name: "stoloto_ticket_id", Kind: TxColumnInt64},
		{Name: "reserved_38", Kind: TxColumnInt64},
		{Name: "alc_code", Kind: TxColumnString},
		{Name: "reserved_40", Kind: TxColumnFloat64},
		{Name: "prescription_data_1", Kind: TxColumnString},
		{Name: "prescription_data_2", Kind: TxColumnString},
		{Name: "position_coupons", Kind: TxColumnString},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_item_tax_4_14": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "dimension_value_codes", Kind: TxColumnString},
		{Name: "tax_group_code", Kind: TxColumnInt64},
		{Name: "tax_rate_code", Kind: TxColumnInt64},
		{Name: "tax_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "total_amount_base_with_discounts", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "amount_base_without_discounts", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_mark_unit_121": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnInt64},
		{Name: "reserved_16", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnString},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "reserved_26", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnString},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "reserved_40", Kind: TxColumnFloat64},
		{Name: "reserved_41", Kind: TxColumnString},
		{Name: "reserved_42", Kind: TxColumnString},
		{Name: "reserved_43", Kind: TxColumnInt64},
	},
	"tx_modifier_registration_30": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "item_identifier", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "item_quantity", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "modifier_code", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_modifier_storno_31": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "item_identifier", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "item_quantity", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "document_print_group_code", Kind: TxColumnInt64},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "modifier_code", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_non_fiscal_payment_36": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "gift_card_number", Kind: TxColumnString},
		{Name: "payment_type_code", Kind: TxColumnString},
		{Name: "payment_type_operation", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_non_fiscal_payment_86": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "gift_card_number", Kind: TxColumnString},
		{Name: "payment_type_code", Kind: TxColumnString},
		{Name: "payment_type_operation", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "payment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "counter_type_code", Kind: TxColumnInt64},
		{Name: "counter_code", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_position_discount_15": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_position_discount_17": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "discount_info", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "discount_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "discount_value", Kind: TxColumnFloat64},
		{Name: "discount_amount_base", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_prepayment_34": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "prepayment_type", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "prepayment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_prepayment_84": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "prepayment_type", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "prepayment_amount", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_report_z_63": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "shift_revenue", Kind: TxColumnFloat64},
		{Name: "cash_in_drawer", Kind: TxColumnFloat64},
		{Name: "shift_income_total", Kind: TxColumnFloat64},
		{Name: "reserved_13", Kind: TxColumnInt64},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "reserved_23", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnString},
		{Name: "cash_document_number", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "unreported_docs_count", Kind: TxColumnString},
		{Name: "exchange_error_codes", Kind: TxColumnString},
		{Name: "earliest_unreported_doc_datetime", Kind: TxColumnDate},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_report_zless_60": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "shift_revenue", Kind: TxColumnFloat64},
		{Name: "cash_in_drawer", Kind: TxColumnFloat64},
		{Name: "shift_income_total", Kind: TxColumnFloat64},
		{Name: "reserved_13", Kind: TxColumnInt64},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "reserved_23", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnString},
		{Name: "cash_document_number", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "unreported_docs_count", Kind: TxColumnString},
		{Name: "exchange_error_codes", Kind: TxColumnString},
		{Name: "earliest_unreported_doc_datetime", Kind: TxColumnDate},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_shift_close_61": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "shift_revenue", Kind: TxColumnFloat64},
		{Name: "cash_in_drawer", Kind: TxColumnFloat64},
		{Name: "shift_income_total", Kind: TxColumnFloat64},
		{Name: "reserved_13", Kind: TxColumnInt64},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "reserved_23", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnString},
		{Name: "cash_document_number", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "unreported_docs_count", Kind: TxColumnString},
		{Name: "exchange_error_codes", Kind: TxColumnString},
		{Name: "earliest_unreported_doc_datetime", Kind: TxColumnDate},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_shift_open_62": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "shift_revenue", Kind: TxColumnFloat64},
		{Name: "cash_in_drawer", Kind: TxColumnFloat64},
		{Name: "shift_income_total", Kind: TxColumnFloat64},
		{Name: "reserved_13", Kind: TxColumnInt64},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "reserved_23", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnString},
		{Name: "cash_document_number", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "unreported_docs_count", Kind: TxColumnString},
		{Name: "exchange_error_codes", Kind: TxColumnString},
		{Name: "earliest_unreported_doc_datetime", Kind: TxColumnDate},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_shift_open_doc_64": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "shift_revenue", Kind: TxColumnFloat64},
		{Name: "cash_in_drawer", Kind: TxColumnFloat64},
		{Name: "shift_income_total", Kind: TxColumnFloat64},
		{Name: "reserved_13", Kind: TxColumnInt64},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnFloat64},
		{Name: "reserved_16", Kind: TxColumnFloat64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "reserved_23", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnString},
		{Name: "cash_document_number", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "unreported_docs_count", Kind: TxColumnString},
		{Name: "exchange_error_codes", Kind: TxColumnString},
		{Name: "earliest_unreported_doc_datetime", Kind: TxColumnDate},
		{Name: "reserved_44", Kind: TxColumnDate},
	},
	"tx_special_price_3": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "price_list_code", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "price_type", Kind: TxColumnFloat64, AllowZero: true},
		{Name: "special_price", Kind: TxColumnFloat64},
		{Name: "product_card_price", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "promotion_code", Kind: TxColumnInt64},
		{Name: "event_code", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "reserved_28", Kind: TxColumnInt64},
		{Name: "reserved_29", Kind: TxColumnInt64},
		{Name: "reserved_30", Kind: TxColumnString},
		{Name: "reserved_31", Kind: TxColumnInt64},
		{Name: "reserved_32", Kind: TxColumnInt64},
		{Name: "reserved_33", Kind: TxColumnString},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
	},
	"tx_vat_kkt_88": {
		{Name: "transaction_id_unique", Kind: TxColumnInt64},
		{Name: "source_folder", Kind: TxColumnSource},
		{Name: "transaction_date", Kind: TxColumnDate},
		{Name: "transaction_time", Kind: TxColumnTime},
		{Name: "transaction_type", Kind: TxColumnInt64},
		{Name: "cash_register_code", Kind: TxColumnInt64},
		{Name: "document_number", Kind: TxColumnInt64},
		{Name: "cashier_code", Kind: TxColumnInt64},
		{Name: "reserved_8", Kind: TxColumnString},
		{Name: "reserved_9", Kind: TxColumnString},
		{Name: "reserved_10", Kind: TxColumnFloat64},
		{Name: "reserved_11", Kind: TxColumnFloat64},
		{Name: "reserved_12", Kind: TxColumnFloat64},
		{Name: "operation_type", Kind: TxColumnInt64, AllowZero: true},
		{Name: "shift_number", Kind: TxColumnInt64},
		{Name: "reserved_15", Kind: TxColumnInt64},
		{Name: "reserved_16", Kind: TxColumnInt64},
		{Name: "print_group_code", Kind: TxColumnInt64, AllowZero: true},
		{Name: "reserved_18", Kind: TxColumnString},
		{Name: "reserved_19", Kind: TxColumnInt64},
		{Name: "reserved_20", Kind: TxColumnFloat64},
		{Name: "reserved_21", Kind: TxColumnInt64},
		{Name: "reserved_22", Kind: TxColumnInt64},
		{Name: "document_type_code", Kind: TxColumnInt64},
		{Name: "reserved_24", Kind: TxColumnInt64},
		{Name: "reserved_25", Kind: TxColumnInt64},
		{Name: "document_info", Kind: TxColumnString},
		{Name: "enterprise_id", Kind: TxColumnInt64},
		{Name: "vat_0_amount", Kind: TxColumnFloat64},
		{Name: "vat_10_amount", Kind: TxColumnFloat64},
		{Name: "vat_20_amount", Kind: TxColumnFloat64},
		{Name: "no_vat_amount", Kind: TxColumnFloat64},
		{Name: "vat_10_110_amount", Kind: TxColumnFloat64},
		{Name: "vat_20_120_amount", Kind: TxColumnFloat64},
		{Name: "reserved_34", Kind: TxColumnString},
		{Name: "reserved_35", Kind: TxColumnString},
		{Name: "reserved_36", Kind: TxColumnDate},
		{Name: "reserved_37", Kind: TxColumnInt64},
		{Name: "reserved_38", Kind: TxColumnString},
		{Name: "reserved_39", Kind: TxColumnString},
		{Name: "reserved_43", Kind: TxColumnString},
	},
}

var txInitialisms = map[string]string{
	"id":    "ID",
	"kkt":   "KKT",
	"vat":   "VAT",
	"egais": "EGAIS",
	"ps":    "PS",
	"sku":   "SKU",
	"alc":   "ALC",
}

// ColumnToFieldName converts a snake_case column name to a Go struct field name.
func ColumnToFieldName(name string) string {
	parts := strings.Split(name, "_")
	var b strings.Builder
	prevDigit := false
	for _, part := range parts {
		if part == "" {
			continue
		}
		if isAllDigits(part) {
			if prevDigit {
				b.WriteString("_")
			}
			b.WriteString(part)
			prevDigit = true
			continue
		}
		prevDigit = false
		lower := strings.ToLower(part)
		if initialism, ok := txInitialisms[lower]; ok {
			b.WriteString(initialism)
			continue
		}
		b.WriteString(strings.ToUpper(lower[:1]))
		if len(lower) > 1 {
			b.WriteString(lower[1:])
		}
	}
	return b.String()
}

func isAllDigits(s string) bool {
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return s != ""
}
