#!/usr/bin/env bash

# Generate RabbitMQ credentials file for docker compose without committing secrets.

set -euo pipefail

OUT_FILE=".env.rabbitmq"
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --output)
      OUT_FILE="$2"
      shift 2
      ;;
    *)
      echo "Usage: $0 [--force] [--output <file>]" >&2
      exit 1
      ;;
  esac
done

if [[ -f "$OUT_FILE" && "$FORCE" -ne 1 ]]; then
  echo "File $OUT_FILE already exists. Use --force to overwrite." >&2
  exit 1
fi

random_string() {
  tr -dc 'a-z0-9' < /dev/urandom | head -c "$1"
}

USER="rabbitmq_$(random_string 8)"
PASS="$(random_string 24)"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/gen-rabbitmq-credentials.sh
RABBITMQ_DEFAULT_USER=$USER
RABBITMQ_DEFAULT_PASS=$PASS
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_VHOST=/
RABBITMQ_URL=amqp://$USER:$PASS@rabbitmq:5672/
RABBITMQ_MANAGEMENT_URL=http://rabbitmq:15672
EOF

chmod 600 "$OUT_FILE"
echo "Generated $OUT_FILE with random credentials."
